### ISSUE TITLE
minimap installation

### ISSUE THREAD

**Issue by jilguero888** [beasteers/jupyterlab-minimap#1]
Hi, I am trying to install minimap on jupyterlab with:
jupyter labextension install jupyterlab_minimap

and I get this error:
ValueError: "jupyterlab_minimap" is not a valid npm package

I don't know if this has to do with npm login or not, but I suppose that for only installing a package I don't need npm login.
I also created a package.json file, but it doesn't work.

I am using:
Ubuntu 20.04
Jupyter-lab Version 3.0.16
node -v
v14.17.1
npm -v
6.14.13

I paste the log file:

Node v14.17.1

Yarn configuration loaded.
> /usr/bin/npm pack jupyterlab_minimap
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jupyterlab_minimap - Not found
npm ERR! 404 
npm ERR! 404  'jupyterlab_minimap@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-25T09_39_11_594Z-debug.log

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/labextensions.py", line 167, in run_task
    return any([

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/labextensions.py", line 168, in <listcomp>
    install_extension(

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/commands.py", line 620, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/commands.py", line 1629, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/usr/local/lib/python3.8/dist-packages/jupyterlab/commands.py", line 1708, in _extract_package
    raise ValueError(msg % source)

ValueError: "jupyterlab_minimap" is not a valid npm package

Exiting application: lab

Thank you.

**Comment by beasteers** [comment]
hi so I don't know what ever happened to this but it looks like I never really did anything with this repo. I'm just going to delete the repo because it's basically just boilerplate atm and I don't have the time/need to finish it.

Sorry for the confusion/disappointment! This isn't the same thing, but it serves a similar purpose: https://github.com/jupyterlab/jupyterlab-toc
